AWSTemplateFormatVersion: "2010-09-09"
Description: "Building an EC2 Instance"
Parameters:
  KeyName:
    Description: "The name of the key pair to use for SSH access"
    Type: String
    # Type: AWS::EC2::KeyPair::KeyName
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-00a1270ce1e007c27
      # Use 'SecurityGroups for default VPC instead of SecurityGroupIds'
      SecurityGroups: ["WebDMZ"] # needs to be the Group Name of the Security Group
      Tags:
        - Key: Name
          Value: "Server"
Outputs:
  ServerPublicDns:
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName